/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.thedivazo.testlibrary;

public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }
}
